version: 2.1

executors:
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
    docker:
        parameters:
            with_deploy:
            type: boolean
            default: false
        executor: docker
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.09.0-ce
            - run:
                name: Build
                command: |
                    docker build -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/decision-discord:latest .
            - when:
                condition: <<parameters.with_deploy>>
                steps:
                    - run:
                        name: Deploy
                        command: |
                            docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASS
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/decision-discord:latest
                            
workflows:
    version: 2
    build:
        jobs:
            - docker
                name: auto-build
                with_deploy: true
                filters:
                    branches:
                        only: master